#!/usr/bin/env python
""" vssump Compute local 1x1x1 mean using the buffer method """
from v4 import vx
from vxbuffer import *
import sys

vargs = vx.vaparse( "if= of= n= -v  - ")


if '-' in vargs:
   print ("vssump 1x1xn local temporal mean filter")
   print ("if= input file")
   print ("of= output file")
   print ("n= number of frames")
   print ("[-v] verbose mode for very small images")
   sys.exit(0)

for arg in ['if', 'of', 'n']:
   if arg not in vargs:
       print ('vssump error: required parameter %s is missing' % arg)
       sys.exit(1)

optv = '-v' in vargs
nn = int(vargs['n'])

invx = vxIbuf(vargs['if'], nn);
outvx = vxObuf(vargs['of'] ); 
im = invx.i
imr = empty( im[0].shape, dtype=im.dtype);
while invx.read():
    im = invx.i
    num1 = 0
    num2 = 0
    num3 = 0
    
    for y in range(im.shape[1] ):
        for x in range(im.shape[2]):
             num1 = im[0][y][x]
             num2 = im[1][y][x]
             num3 = im[2][y][x]

             if num1 >= num2 and num1 <= num3:
                 imr[y][x] = num1
             elif num1 <= num2 and num1 >= num3:
                 imr[y][x] = num1
             elif num2 <= num1 and num2 >= num3:
                 imr[y][x] = num2
             elif num2 >= num1 and num2 <= num3:
                 imr[y][x] = num2
             else:
                 imr[y][x] = num3
                 
             


    if optv:
       print (imr)						   
    outvx.add(imr)

outvx.close()

