#!/usr/bin/env python
""" v3lpf: 3x3x3  low pass filter for 3D images

"""
from v4 import vx
import sys
import numpy as np

def v3lpf ( img ) :
 """  3x3x3 low pass filter vx.Vx struct
 """
 im = img.i
 tmimage = vx.Vx( img ) 
 tmimage.embedim((1,1,1,1,1,1))
 tm = tmimage.i
 for z in range(1, im.shape[0]):
    for y in range(1, im.shape[1]):
        for x in range(1, im.shape[2]):
            # Calculate partial derivative in x,y,z directions
            gz = abs(tm[z, y, x] - tm[z+1, y, x]) + abs(tm[z, y, x] - tm[z-1, y, x])
            gy = abs(tm[z, y, x] - tm[z, y+1, x]) + abs(tm[z, y, x] - tm[z, y-1, x])
            gx = abs(tm[z, y, x] - tm[z, y, x+1]) + abs(tm[z, y, x] - tm[z, y, x-1])

            im[z, y, x] = gx + gy + gz

vargs = vx.vaparse( "if= of= -v  - ")
if '-' in vargs:
   print ("v3lpf 3D low pass filter")
   print ("if= input file")
   print ("of= output file")
   print ("[-v] verbose mode")
   sys.exit(0)

for arg in ['if', 'of']:
   if arg not in vargs:
       print ('v3lpf error: required parameter %s is missing' % arg)
       sys.exit(1)
optv = '-v' in vargs

ximage = vx.Vx( vargs['if'] )   ;#read image
v3lpf(ximage)                 ;#process image
if optv:
   print (ximage.i)             ;# for very small images
ximage.write(vargs['of'])       ;# Write the result file
